routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [\App\Http\Controllers\ProductController::class, 'index'])->name('index');
Route::get('/about', [\App\Http\Controllers\AboutUsController::class, 'index'])->name('aboutUs');

Route::resource('products', \App\Http\Controllers\ProductController::class)->except('index');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'description', 'price'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/AboutUsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AboutUsController extends Controller
{
    public function index()
    {
        return view('contacts.aboutUs');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductStoreRequest;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{

    public function index()
    {
        $products = DB::table('products')->simplePaginate(9);
        return view('index', compact('products'));
    }

    public function create()
    {
        return view('products.productCreate');
    }

    public function store(ProductStoreRequest $request)
    {
        $validate = $request->validated();
        $product = new Product($validate);
        $product->save();
        return redirect('/')->with('status', __('Продукт успешно создан'));
    }

    public function show(string $id)
    {
        $product = Product::find($id);
        return view('products.productShow', compact('product'));
    }

    public function edit(string $id)
    {
        $product = Product::find($id);
        return view('products.productEdit', compact('product'));
    }

    public function update(ProductStoreRequest $request, string $id)
    {
        $validated = $request->validated();
        $product = Product::find($id);
        $product->update($validated);
        return redirect('/')->with('status', __('Продукт отредактирован'));
    }

    public function destroy(string $id)
    {
        $product = Product::find($id);
        $product->delete();
        return redirect('/')->with('status', __('Продукт удалён'));
    }
}

resources/views/contacts/aboutUs.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div>
            <h1 id="about-us-title">
               {{__('О нас')}}
            </h1>
        </div>
        <div>
            <p id="about-us-body">
                Чтобы показать масштаб компании, следует добавить коллективное фото работников (если команда действительно велика). Фотография, сделанная в неофициальной атмосфере, — это даже плюс. Большое количество людей, объединенных общей деятельностью, улыбающиеся лица, красноречивая подпись — все это на странице о Ceros, которая позиционирует себя как первая компания, специалисты которой начали работать отдаленно: «Черт возьми. Нас около 400. И мы продолжаем расти. Интенсивно. В 15 странах».
            </p>
        </div>
        <div>
            <h2 id="contact-title">
                {{__('Контакты')}}
            </h2>
        </div>
        <div>
            <p id="contact-phone">
                {{__('Телефон')}}: +996 321 2312 3211
            </p><br>
            <p id="contact-email">
                {{__('Адрес электронной почты')}}: SuperPuper@mail.com
            </p>
        </div>
    </div>
@endsection

resources/views/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container" style="margin-bottom: 100px">
        <div style="justify-content: right">
            <a href="{{route('products.create')}}" id="product-create-link">{{__('Создать продукт')}}</a>
        </div>
        <div>
            <h1 id="index-title">
                {{__('Список наших товаров')}}
            </h1>
        </div>
        <div class="row">
            @foreach($products as $product)
                <div class="col-lg-3 col-md-4 col-sm-12 cards">
                    <a class="product-name" href="{{route('products.show', ['product' => $product->id])}}" style="justify-content: center; padding-left: 60px">
                        {{$product->name}}
                    </a>
                    <div id="delete-icon">
                        <div>
                                <form method="post" action="{{route('products.destroy', ['product' => $product->id])}}">
                                    @method('DELETE')
                                    @csrf
                                    <button style="background-color: transparent; border: none; color: blue" id="delete-button" type="submit"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-minus" viewBox="0 0 16 16">
                                            <path d="M5.5 9a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H6a.5.5 0 0 1-.5-.5"/>
                                            <path d="M14 4.5V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h5.5zm-3 0A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4.5z"/>
                                        </svg></button>
                                </form>
                        </div>
                    </div>
                    <div id="edit-icon">
                        <a href="{{route('products.edit', ['product' => $product->id])}}">
                            <svg style="text-align: right" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.5.5 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11z"/>
                            </svg>
                        </a>
                    </div>
                    <br>
                    <p class="product-description">{{$product->description}}</p><br>
                    <p class="product-price"><strong>{{$product->price}} {{__('сом')}}</strong></p>
                </div>
            @endforeach
        </div>
        {{$products->links()}}
    </div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Laravel</title>
    <!-- Fonts -->
    <link href="https://fonts.bunny.net/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">
    @vite(['resources/js/app.js', 'resources/sass/app.scss'])
</head>
<body class="antialiased">
<nav style="color: skyblue" class="navbar navbar-expand-lg bg-body-tertiary">
    <div style="background-color: skyblue" class="container-fluid">
        <a style="margin-left: 40px; font-size: 30px" class="navbar-brand" href="{{route('index')}}">Main Page</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a style="margin-left: 1300px" class="navbar-brand" href="{{route('aboutUs')}}">О нас</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        </div>
    </div>
</nav>
<div class="container-fluid">
    @if(session('status'))
        <div class="row">
            <div class="col">
                <div class="alert alert-primary" role="alert">
                    {{session('status')}}
                </div>
            </div>
        </div>
@endif
        </div>
@yield('content')
<footer id="footer">
        <h3 id="copyright">Copyright 2024</h3>
</footer>
</body>
</html>

resources/views/products/productCreate.blade.php
@extends('layouts.app')
@section('content')
    <div id="form-create-container" class="container">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div>
            <h1>{{__('Создание продукта')}}</h1>
        </div>
        <div>
            <form method="POST" action="{{route('products.store')}}">
                @method('POST')
                @csrf
                <div>
                    <p>{{__('Название товара')}}</p><br>
                    <input name="{{__('name')}}" required placeholder="{{__('Введите название товара')}}" value="{{old('name')}}">
                </div>
                <div>
                    <p>{{__('Описане товара')}}</p><br>
                    <textarea placeholder="{{__('Описание товара')}}" name="description" required>{{old('description')}}</textarea>
                </div>
                <div>
                    <p>{{__('Цена товара')}}</p><br>
                    <input type="number" name="price" placeholder="{{__('Введите цену товара')}}" required value="{{old('price')}}" step="0.01">
                </div>
                <button id="create-button" type="submit">{{__('Создать товар')}}</button>
            </form>
        </div>
    </div>
@endsection

resources/views/products/productEdit.blade.php
@extends('layouts.app')
@section('content')
    <div id="form-create-container" class="container">
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div>
            <h1>{{__('Создание продукта')}}</h1>
        </div>
        <div>
            <form method="POST" action="{{route('products.update', ['product' => $product->id])}}">
                @method('PUT')
                @csrf
                <div>
                    <p>{{__('Название товара')}}</p><br>
                    <input name="name" required placeholder="{{__('Введите название товара')}}" value="{{$product->name}}">
                </div>
                <div>
                    <p>{{__('Описане товара')}}</p><br>
                    <textarea placeholder="{{__('Описание товара')}}" name="description" required>{{$product->description}}</textarea>
                </div>
                <div>
                    <p>{{__('Цена товара')}}</p><br>
                    <input type="number" name="price" placeholder="{{__('Введите цену товара')}}" required value="{{$product->price}}" step="0.01">
                </div>
                <button id="create-button" type="submit">{{__('Отредактировать товар')}}</button>
            </form>
        </div>
    </div>
@endsection

resources/views/products/productShow.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div>
            <h1 id="product-show-title">{{__('Страница товара')}}: {{$product->name}}</h1>
        </div>
        <div>
            <h2 id="product-description-title">{{__('Описание')}}:</h2>
        </div>
        <div>
            <p id="product-description-body">{{$product->description}}</p>
        </div>
        <div>
            <h2 id="product-price-title">{{__('Цена товара')}}:</h2><br>
            <p id="product-price">{{$product->price}} сом</p>
        </div>
    </div>
@endsection